version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: koshou1010/swm-tools-backend-image:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: koshou1010/swm-tools-frontend-image:latest